export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SIGNUP = "SIGNUP";
export const REMOVEFROMCART = "REMOVEFROMCART";
export const ADDTOCART = "ADDTOCART";
export const SETSEARCH = "SETSEARCH";
export const RESETSEARCH = "RESETSEARCH";
export const FAVORITES ="FAVORITES";
export const UPDATE_COUNT = 'UPDATE_COUNT';
export const PURCHASE = 'PURCHASE';
export const OPENCART = 'OPENCART';
export const CLOSECART = 'CLOSECART';
export const LOAD_ALL_CART_ITEMS = 'LOAD_ALL_CART_ITEMS';
export const CLEAR_CART = 'CLEAR_CART'
export const PURCHASE_FROM_CART = 'PURCHASE_FROM_CART'
export const SET_CATEGORY_TREE = "SET_CATEGORY_TREE";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const UPDATE_PRODUCTS = "category/UPDATE_PRODUCTS";